import random

def analyze_ip(ip: str) -> dict:
    """Simulates a Threat Intelligence API lookup (like VirusTotal or AlienVault OTX)."""
    if not ip or ip.startswith("10.") or ip.startswith("192.168.") or ip.startswith("127."):
        return {"ip": ip, "status": "benign", "tags": ["internal", "rfc1918"], "provider": "Local Context"}

    # Hardcoded malicious IPs from our simulation scenarios
    if ip == "185.10.10.20":
        return {"ip": ip, "status": "malicious", "tags": ["tor_exit_node", "exfiltration_node"], "provider": "SimulatedTI", "confidence": 99}
    if ip == "45.33.32.156": # A generic external attacker IP
        return {"ip": ip, "status": "malicious", "tags": ["c2_server", "cobalt_strike"], "provider": "SimulatedTI", "confidence": 95}

    # For any other external IPs randomly generated by our simulator, randomly flag them to show off the engine
    is_malicious = random.random() > 0.4
    if is_malicious:
        tags = random.sample(["botnet", "scanner", "phishing_infrastructure", "malware_distribution", "anonymous_vpn"], k=random.randint(1, 3))
        return {"ip": ip, "status": "malicious", "tags": tags, "provider": "SimulatedTI", "confidence": random.randint(60, 95)}

    return {"ip": ip, "status": "suspicious", "tags": ["hosting_provider", "proxy"], "provider": "SimulatedTI", "confidence": random.randint(20, 50)}